import { useState } from 'react'
import type { BriefOutput } from '../../data/types'

interface EmailPreviewProps {
  brief: BriefOutput
}

function formatPct(pct: number): string {
  const sign = pct > 0 ? '+' : ''
  return `${sign}${(pct * 100).toFixed(0)}%`
}

export default function EmailPreview({ brief }: EmailPreviewProps) {
  return (
    <div className="space-y-6">
      <p className="text-xs text-muted">Preview of the daily email report</p>

      {/* Email Card */}
      <div className="rounded-lg border border-border bg-base space-y-0">
        {/* A. Email Header */}
        <div className="border-b border-border px-5 py-3 space-y-1">
          <p className="text-xs text-muted">Subject:</p>
          <p className="text-sm font-medium text-primary">
            AI Traffic Brief | Last 24h Unique User Changes
          </p>
        </div>

        {/* Body */}
        <div className="px-5 py-4 space-y-4">
          {/* B. Summary */}
          <p className="text-sm text-primary">{brief.summary}</p>

          {/* C. Key Changes */}
          <div className="space-y-2">
            <p className="text-xs font-semibold text-primary">Key Changes</p>
            <ul className="space-y-1">
              {brief.keySignals.map((signal, i) => (
                <li key={i} className="text-xs text-secondary">• {signal}</li>
              ))}
            </ul>
          </div>

          {/* Signal Overview */}
          <div className="grid grid-cols-2 gap-4">
            {brief.topDrops.length > 0 && (
              <div className="space-y-1.5">
                <p className="text-xs font-semibold text-storm">Drops / Risks</p>
                {brief.topDrops.map((d, i) => (
                  <div key={i} className="flex items-center justify-between text-xs">
                    <span className="text-secondary truncate">{d.name}</span>
                    <span className="text-storm font-mono ml-2">{formatPct(d.usersChangePct)}</span>
                  </div>
                ))}
              </div>
            )}
            {brief.topRises.length > 0 && (
              <div className="space-y-1.5">
                <p className="text-xs font-semibold text-sunny">Rises / Opportunities</p>
                {brief.topRises.map((r, i) => (
                  <div key={i} className="flex items-center justify-between text-xs">
                    <span className="text-secondary truncate">{r.name}</span>
                    <span className="text-sunny font-mono ml-2">{formatPct(r.usersChangePct)}</span>
                  </div>
                ))}
              </div>
            )}
          </div>

          {/* D. Alerts */}
          {brief.alerts.length > 0 && (
            <div className="space-y-1.5 border-t border-border pt-3">
              <p className="text-xs font-semibold text-cloudy">Alerts</p>
              {brief.alerts.slice(0, 3).map((a, i) => (
                <div key={i} className="flex items-center justify-between text-xs">
                  <span className="text-secondary">{a.name} <span className="text-muted">({a.dimension})</span></span>
                  <span className={`font-mono ${a.usersChangePct > 0 ? 'text-spike' : 'text-drop'}`}>
                    {formatPct(a.usersChangePct)}
                  </span>
                </div>
              ))}
            </div>
          )}

          {/* Footer */}
          <div className="border-t border-border pt-3">
            <p className="text-[10px] text-muted">
              Generated by AI Traffic Brief · Demo preview only
            </p>
          </div>
        </div>
      </div>

      {/* E. Subscription Block */}
      <EmailSubscriptionBlock />
    </div>
  )
}

/* ── Inline Email Subscription Block ── */

function EmailSubscriptionBlock() {
  const [frequency, setFrequency] = useState('daily')
  const [enabled, setEnabled] = useState(false)
  const [saved, setSaved] = useState(false)

  const handleSave = () => {
    setSaved(true)
    setTimeout(() => setSaved(false), 3000)
  }

  return (
    <div className="rounded-lg border border-border/60 bg-surface/50 p-4 space-y-4">
      <p className="text-xs font-medium text-secondary">Subscription Settings</p>

      <div className="grid grid-cols-2 gap-4">
        {/* Channel (fixed to Email) */}
        <div className="space-y-1.5">
          <label className="text-[11px] text-muted">Channel</label>
          <div className="w-full rounded-md border border-border bg-base px-2.5 py-1.5 text-xs text-primary">
            Email
          </div>
        </div>

        {/* Frequency */}
        <div className="space-y-1.5">
          <label className="text-[11px] text-muted">Frequency</label>
          <select
            value={frequency}
            onChange={e => setFrequency(e.target.value)}
            className="w-full rounded-md border border-border bg-base px-2.5 py-1.5 text-xs text-primary outline-none focus:border-brand"
          >
            <option value="daily">Daily</option>
            <option value="weekly">Weekly</option>
            <option value="anomaly">On anomaly</option>
          </select>
        </div>
      </div>

      {/* Toggle + Save */}
      <div className="flex items-center justify-between">
        <div className="flex items-center gap-2">
          <button
            onClick={() => setEnabled(!enabled)}
            className={`relative h-5 w-9 rounded-full transition-colors ${enabled ? 'bg-brand' : 'bg-border'}`}
          >
            <span
              className={`absolute top-0.5 h-4 w-4 rounded-full bg-white transition-transform ${enabled ? 'left-[18px]' : 'left-0.5'}`}
            />
          </button>
          <span className="text-xs text-secondary">{enabled ? 'Subscribed' : 'Off'}</span>
        </div>

        <button
          onClick={handleSave}
          className="rounded-md bg-brand/10 px-3 py-1.5 text-xs font-medium text-brand transition-colors hover:bg-brand/20"
        >
          Save
        </button>
      </div>

      {saved && (
        <p className="text-center text-[11px] text-brand">Preferences saved (demo mode)</p>
      )}
    </div>
  )
}
